Dces-583 use config vars secret
ministryofjustice/laa-dces-report-service pull request #121
Opened 2024-11-05 18:20 UTC by vvartakMoJ

## What

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-583)

Changes to read the config settings like cron schedule and email recipients from a new AWS/K8S managed secret instead of the values files to make them easier to change when needed.

Bumped versions of Spring and other dependencies and removed unnecessary hard-coded versions.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2024-11-05 23:08 UTC, dconneely reviewed
Happy to approve as-is, but couple of questions.

2024-11-05 23:08 UTC, dconneely commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/scheduler/DcesReportScheduler.java
> +    @Scheduled(cron = "${spring.scheduling.cron.contributions.monthly:-}")
Do we need a story to prevent multiple instances of the report-service from reporting multiple times (similar to DCES-554 for the DRC Integration)? Unfortunately, there's no database, so not sure how you'd lock though.

2024-11-06 09:10 UTC, vvartakMoJ commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/scheduler/DcesReportScheduler.java
> +    @Scheduled(cron = "${spring.scheduling.cron.contributions.monthly:-}")
I did think about that, but considering that normally (i.e. outside testing or transition, like now) it is only run once a month, the _maxReplicas: 1_ setting should avoid that scenario. And the consequences of being run more than once is only multiple emails, so not too serious either.

2024-11-06 10:18 UTC, vvartakMoJ commented on dces-report-service/build.gradle
>      implementation "io.micrometer:micrometer-tracing-bom:$versions.micrometerio"
Done. And I'm only following your lead!

2024-11-06 11:00 UTC, dconneely requested changes

2024-11-06 11:00 UTC, dconneely commented on dces-report-service/build.gradle
> -    implementation "io.micrometer:micrometer-tracing-bom:$versions.micrometerio"
Hi Vid, I actually meant to only remove the first line 'io.micrometer:micrometer-tracing-**bom**:$versions.micrometerio'. We probably do need the next two lines (micrometer-tracing-bridge-brave and micrometer-registry-prometheus) for our monitoring to work.

Interestingly, if the code still compiled without these lines, then you can make them `runtimeOnly` configuration deps instead of `implementation`.

But I think they do need to be added back

2024-11-06 11:04 UTC, dconneely commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/scheduler/DcesReportScheduler.java
> +    @Scheduled(cron = "${spring.scheduling.cron.contributions.monthly:-}")
Got it. We could consider using a Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to run a console application, instead of running as a web application all the time (to only do something once a month).

2024-11-06 11:05 UTC, dconneely commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/scheduler/DcesReportScheduler.java
> +    @Scheduled(cron = "${spring.scheduling.cron.contributions.monthly:-}")
(But obviously, that's a bigger decision and certainly another story :)).

2024-11-06 11:31 UTC, dconneely approved these changes

2024-11-06 12:12 UTC, merged