Dces 22 fdc matt api xml endpoint
ministryofjustice/laa-dces-report-service pull request #18
Opened 2023-06-28 09:05 UTC by vloruncg

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)

Describe what you did and why.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2023-07-03 08:45 UTC, tanovellino commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/maatapi/config/ServicesConfiguration.java
> +    public static class EformApi {
Why do we need the eFormApi ?

2023-07-03 08:56 UTC, vloruncg commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/maatapi/config/ServicesConfiguration.java
> +    public static class EformApi {
**eFormApi** is the moniker being used in other projects internal to refer to the MAAT API, so using that convention will help transparency and consistency across projects. Additional having a static POJO representing the service configuration will provide a pattern to extend the repository with additional services that maybe added in future iterations.

2023-07-03 10:09 UTC, atharmajeed requested changes

2023-07-03 10:09 UTC, atharmajeed commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/service/FdcFilesReportService.java
> +        // validate date period
Looks like we don't need this comment

2023-07-03 10:09 UTC, atharmajeed commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/maatapi/config/ServicesConfiguration.java
> +    public static class EformApi {
The name doesn't seems right and also I am not sure why we need this. There is some Cognito integration and it might be related to that.

2023-07-03 10:09 UTC, atharmajeed commented on dces-report-service/src/test/java/uk/gov/justice/laa/crime/dces/report/maatapi/MaatApiWebClientFactoryTest.java
>      private static MockWebServer mockWebServer;
Highlighting this part, it looks like we are using both MockWebServer and WireMock which are the same. So I'd suggest we should only use one of them. Should we just use the wiremock and remove this at all.  Happy to go either way.

2023-07-03 11:40 UTC, vloruncg commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/maatapi/client/FdcFilesClient.java
> +    @GetExchange("/fdc/{startDate}/{endDate}")
Not sure the best way to implement this, based on my own testing and this issue [thread](https://github.com/spring-projects/spring-framework/issues/28492), it is not possible to access the application properties in conjunction with the "@HttpExchange" annotation verbs. The work possible arounds In my opinion would be messy and non-intuitive and would break the benefits that the proxy client service offers. What are your thoughts.

2023-07-04 08:37 UTC, vloruncg commented on dces-report-service/src/main/java/uk/gov/justice/laa/crime/dces/report/maatapi/config/ServicesConfiguration.java
> +    public static class EformApi {
Upon reflection the reasoning behind the naming in other projects is because of source/ endpoints being utilised (eforms), however functionally it was still the Maat API that was the medium for these request, so i've renamed the service and configuration models.
@atharmajeed I would suggest Cognito credentials/ auth endpoints be modelled similarly as an additional [authorisation] service.

2023-07-04 08:48 UTC, atharmajeed approved these changes

2023-07-04 10:39 UTC, merged